### ISSUE TITLE
Update? What happened to this project?

### ISSUE THREAD

**Issue by derkrasseleo** [YellowOSM/YellowOSM#77]
Would be interesting to know what happened to this project.

**Comment by flowolf** [comment]
Hi!

thanks for reaching out.

We, Daniel and I, are currently busy with day jobs and family, so we don't get to do much any more.

You are welcome to fork it. 

A version of it is online at yellowosm.com, it's not well maintained and with sometimes out of date data. also data was always only available for DE,AT and CH. We could not afford bigger servers for a world view.

hth

**Comment by derkrasseleo** [comment]
Thank you for the quick reply. That's unfortunate, but I hope you don't give up on this project, as it would be a great incentive for companies to contribute to OSM.
